# Generated by Django 3.0.3 on 2020-02-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headPage', '0002_auto_20200214_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(help_text='Заголовок', max_length=200)),
                ('description', models.TextField(help_text='Описание')),
            ],
        ),
    ]
