# Generated by Django 3.0.3 on 2020-02-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headPage', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discript', models.TextField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
