# Generated by Django 3.0.3 on 2020-02-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headPage', '0004_tovar'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tovar',
            table='tovar',
        ),
    ]
