# Generated by Django 3.0.3 on 2020-03-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headPage', '0006_mymenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymenu',
            name='level',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
