# Generated by Django 3.0.3 on 2020-03-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headPage', '0007_mymenu_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymenu',
            options={'ordering': ['l1']},
        ),
        migrations.AlterField(
            model_name='mymenu',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
