# Generated by Django 3.0.3 on 2020-03-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headPage', '0008_auto_20200319_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymenu',
            name='content',
        ),
    ]
