# Generated by Django 3.0.3 on 2020-03-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headPage', '0009_remove_mymenu_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymenu',
            name='content',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
