# Generated by Django 3.0.3 on 2020-03-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headPage', '0010_mymenu_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymenu',
            name='link',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
