# Generated by Django 3.0.3 on 2020-03-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headPage', '0011_mymenu_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymenu',
            name='activ',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
